### PR TITLE
[WIP] RPM spec for compliance-masonry

### PR DESCRIPTION
**Pull request by shawndwells**
Beginning to work on packaging compliance-masonry for EPEL and potential inclusion in RHEL (+derivatives). Submitting WIP to publicly have something to show/share/build conversation around.

### CODE REVIEW

**Comment by shawndwells** [comment]
To do:

- [X] Create initial RPM spec

- [ ] For Phase 1, update RPM spec to call referenced vendoring sources from GitHub, go ahead and compile them for now. Ultimately, need to package these independently.

- [ ] Update docs for packages needed on RPM build host ('make rpms')
- [ ] Create RPM makefile
- [ ] Create EPEL entries for compliance-masonry

**Comment by jcscottiii** [comment]
@shawndwells i know we talked yesterday about an individual package per dependency but came across this https://github.com/mh-cbon/go-bin-rpm
wonder how much this could help.

**Comment by shawndwells** [comment]
Thanks @jcscottiii. Part of the problem is golang vendoring. For example, to build compliance-masonry:

``
$ pwd
/var/www/html/opencontrol/compliance-masonry
[shawn@devbox compliance-masonry]$ ll vendor/github.com/
total 0
drwxrwxr-x. 3 shawn shawn 19 Apr 25 22:47 blang
drwxrwxr-x. 3 shawn shawn 16 Apr 25 22:47 codegangsta
drwxrwxr-x. 3 shawn shawn 20 Apr 25 22:47 davecgh
drwxrwxr-x. 3 shawn shawn 21 Apr 25 22:47 go-forks
drwxrwxr-x. 3 shawn shawn 21 Apr 25 22:47 golang
drwxrwxr-x. 6 shawn shawn 50 Apr 25 22:47 go-utils
drwxrwxr-x. 3 shawn shawn 16 Apr 25 22:47 Masterminds
drwxrwxr-x. 4 shawn shawn 32 Apr 25 22:47 onsi
drwxrwxr-x. 3 shawn shawn 23 Apr 25 22:47 pmezard
drwxrwxr-x. 4 shawn shawn 31 Apr 25 22:47 stretchr
drwxrwxr-x. 3 shawn shawn 22 Apr 25 22:47 tg
drwxrwxr-x. 3 shawn shawn 16 Apr 25 22:47 urfave
drwxrwxr-x. 3 shawn shawn 19 Apr 25 22:47 vektra
``

Each one of the above needs to be individually packaged.... which means *their* dependencies need packaging too. I've started EMailing with some developers who package golang libraries and apps in RHEL to see how they handle this.

**Comment by shawndwells** [comment]
@redhatrises handling packaging, closing this

**Pull request closed without merging**
