### PR TITLE
gofmt code updates

### PR DESCRIPTION
**Pull request by redhatrises**
ran gofmt on the code

### CODE REVIEW

**Comment by redhatrises** [comment]
codecov patch report can be ignored as nothing as change except for formatting.
Ran gofmt on the code that codeclimate is reporting as a new issue... getting nothing. Looks bogus on codeclimate's part.

**Comment by shawndwells** [comment]
@redhatrises clodeclimate shows one more gofmt error. Could that be addressed as well?

**Comment by redhatrises** [comment]
@shawndwells ran gofmt on the file that code climate is saying is the issue, and nothing is returned

**Comment by shawndwells** [comment]
Hmm, yes, that appears odd after looking closer. The line throwing error:

https://github.com/opencontrol/compliance-masonry/blob/master/commands/get/resources/getter_test.go#L1

doesn't have formatting issues that are readily apparent, and wasn't touched by this PR, so merging.

**Pull request merged**
