### PR TITLE
move docs file into its own package

### PR DESCRIPTION
**Pull request by afeld**
Hey look, I Go'd!

cool gopher

### CODE REVIEW

**Comment by jmcarp** [comment]
LGTM, although I don't have strong opinions about how big packages should be. Should `diff` and `get` also be split out? The [language recommendations](https://blog.golang.org/organizing-go-code) kind of equivocate on this:

> It is easy to just throw everything into a "grab bag" package, but this dilutes the meaning of the package name (as it must encompass a lot of functionality) and forces the users of small parts of the package to compile and link a lot of unrelated code.

> On the other hand, it is also easy to go overboard in splitting your code into small packages, in which case you will likely becomes bogged down in interface design, rather than just getting the job done.

**Comment by afeld** [comment]
👍 Mind if I take care of that separately?

**Comment by jmcarp** [comment]
Sure! I'm basically agnostic about whether that code lives in `main` or in separate packages, just wanted to understand the motivation.

**Comment by dlapiduz** [comment]
LGTM

**Pull request merged**
