### PR TITLE
Move to using go modules

### PR DESCRIPTION
**Pull request by aegershman**
closes https://github.com/opencontrol/compliance-masonry/issues/350

This PR swaps the dependency management system from `dep` to `go mod`. The dependencies were automatically transferred over by `go mod` by it using the existing `Gopkg.toml` content.

It was done using the following commands from this blog post https://blog.golang.org/migrating-to-go-modules

```sh
go mod init github.com/opencontrol/compliance-masonry
go mod tidy
# remove Gopkg.toml and Gopkg.lock
# remove vendor/ directory
```

I'm not 100% confident whether the `vendor` directory should be removed, or if it should be re-vendored specifically using `go mod vendor`, so just giving that heads up

(loosely related sidenotes: this PR could be followed by an addition to .goreleaser (not in this PR, but somewhat related https://github.com/opencontrol/compliance-masonry/pull/354) to have `before` hooks of `go mod tidy`. It'd also be worth considering adding a dependabot listener to check for any `go mod` updates (can create different issue for that), and double-checking the entire build process is happy with using `go mod` for dependencies)

Thanks for anyone's time and consideration 👍 

EDIT should also update https://github.com/opencontrol/compliance-masonry/blob/master/docs/development.md

### CODE REVIEW

**Comment by aegershman** [comment]
Noticing travis, appveyor, and circleci checks failed. makes sense considering it's an entire dependency system being swapped out, but will have to look into what's wrong at a different time; unfortunately pretty swamped at the moment 👍

**Comment by redhatrises** [comment]
> I'm not 100% confident whether the vendor directory should be removed, or if it should be re-vendored specifically using go mod vendor, so just giving that heads up

The vendor directory should be kept. I wouldn't add `go mod tidy` always as it could result in having to fix something regularly. It might be better as a manual task for a release or at some point during the year. If you do want to re-vendor it, just make sure to fix any problems.

**Comment by aegershman** [comment]
@redhatrises sounds good, I'll put back the use of `vendor`ing. I'm new to go modules, though I feel I often advocate for vendoring & storing content as code as much as reasonably possible & semantic version / sha pinning, etc. so I'm not sure why I felt compelled to remove the vendor directory here by default; I did a bit of reading about folks' opinions on go modules that it made more sense [(especially this Reddit thread comment)](https://www.reddit.com/r/golang/comments/a539h6/just_tell_me_how_to_use_go_modules/ebkgf1u/)-- so, my bad, I'll do a bit more reading on things & put it back 👍

**Comment by aegershman** [comment]
Ah, okay so I'm under the impression the unhappiness with appveyor is straightforward enough as appveyor being configured to set itself up with `glide` vs having `go build` just leverage the vendored dependencies by default. I'm not sure where to configure the specific version of `go` used in appveyor, but I think it's defaulting to go 1.13, which I believe needs to be setup with `go build -mod=vendor`? [It should default to using `go build -mod=vendor/` in go 1.14+]

So in `appveyor.yml` we perform [`go get github.com/Masterminds/glide`](https://github.com/opencontrol/compliance-masonry/blob/51541f28950d77f76e982982c22f8aa6982d5b70/appveyor.yml#L20) and set the GOPATH and all that good stuff, but I don't believe we would need to do any of the setup / setting gopath / etc. anymore. 

I'm not particularly familiar with appveyor, but did find this config reference helpful for a once-over: https://www.appveyor.com/docs/build-configuration/ ... but still not 100% sure how to set the specific version of go used? or if that can be configured? apologies, I haven't read that far in yet, just typing this up

from https://ci.appveyor.com/project/opencontrol/compliance-masonry/builds/34875184 

```log
Build started
git clone -q https://github.com/opencontrol/compliance-masonry.git c:\gopath\src\github.com\opencontrol\compliance-masonry
git fetch -q origin +refs/pull/355/merge:
git checkout -qf FETCH_HEAD
...
 https://chocolatey.org/compare
echo %GOPATH%
c:\gopath
go version
go version go1.13.3 windows/amd64
go env
set GO111MODULE=
...
go get github.com/Masterminds/glide
go: finding github.com/Masterminds/glide v0.13.3
go: downloading github.com/Masterminds/glide v0.13.3
go: extracting github.com/Masterminds/glide v0.13.3
go: downloading gopkg.in/yaml.v2 v2.3.1-0.20200602174213-b893565b90ca
go: extracting gopkg.in/yaml.v2 v2.3.1-0.20200602174213-b893565b90ca
go: finding github.com/codegangsta/cli v1.22.4
go: finding github.com/Masterminds/semver v1.5.0
go: downloading github.com/Masterminds/vcs v1.13.1
go: downloading github.com/codegangsta/cli v1.22.4
go: extracting github.com/Masterminds/vcs v1.13.1
go: finding github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/Masterminds/semver v1.5.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/codegangsta/cli v1.22.4
go: extracting github.com/Masterminds/semver v1.5.0
...
go: github.com/Masterminds/glide imports
	github.com/codegangsta/cli: github.com/codegangsta/cli@v1.22.4: parsing go.mod:
	module declares its path as: github.com/urfave/cli
	        but was required as: github.com/codegangsta/cli
Command exited with code 1
```

**Comment by aegershman** [comment]
I believe I figured it out: appveyor's default image is visual-code-2015, which only supports up to go 1.13.x (https://www.appveyor.com/docs/windows-images-software/#golang). So the `-mod=vendor` flag needs to be passed to go commands like go test, go build, etc., in order to force it to look in the vendor/ directory for dependencies (this changed in 1.14+ to be default if the vendor/ dir exists)

This also swaps out the go test command to `go test -mod=vendor ./...` for running tests instead of having to use [`glide novendor`](https://glide.readthedocs.io/en/latest/commands/#glide-novendor-aliased-to-nv) and listing out all the subdirectories in a for loop and such; as of go 1.9, `go test ./...` will ignore trying to run tests within the vendor/ directory, see: https://github.com/golang/go/issues/19090

I know this is the domain of other issues (https://github.com/opencontrol/compliance-masonry/issues/357) but consolidating appveyor/travis into github-actions might help reduce the number of touchpoints. There may be benefit in evaluating to what extent `.goreleaser.yml` could be leveraged to handle building artifacts/outputs, even if they aren't 'released', as a way to consolidate the number of touchpoints of build/test-related code. That's for a different issue though, I know; just putting it out there since it's top-of-mind at the moment

This should be ready for real review. Let me know if there's anything to be reconsidered or reformatted (such as appveyor yml being automatted by vscode-yml) 👍

**Comment by redhatrises** [comment]
I am good with this as this is the way that go is now operating.

**Pull request merged**
