### PR TITLE
Adding the PCI-DSS Standard in the same yaml format

### PR DESCRIPTION
**Pull request by Gergues**
Added the PCI-DSS-MAY2015 standards in the same yaml format used for the NIST-800-53 standard.
Adapted from this source.
https://www.pcisecuritystandards.org/documents/Prioritized_Approach_v3-1.xlsx

### CODE REVIEW

**Comment by joshuamckenty** [comment]
Sweet!

**Comment by mogul** [comment]
Wow, thanks a ton!! Now I think if someone from HHS contributes HIPAA we'll be in great shape...

**Comment by geramirez** [comment]
This is fantastic, @Gergues. Bear with us as we update the schema. 

Also would you mind sharing how you converted from xlsx to yaml?

**Comment by Gergues** [comment]
The conversion was done via Excel, or office libre  calculations.   very simple text replacement and concatenation.

Validation via www.yamllint.com .

Do you want that excel sheet calculations???  
Should i keep them in the same folder ,or under some other folder ??? 

-----Original Message-----

**Comment by geramirez** [comment]
@Gergues we just wanted to see if there was a repeatable way of getting the data for when PCI is updated. In any case! Thanks for the contribution! Looks like it's working with a few tweaks to our script on our end. Thanks!

**Pull request merged**
