### PR TITLE
[WIP] Include files

### PR DESCRIPTION
**Pull request by jcscottiii**

### CODE REVIEW

**Comment by afeld** [comment]
Closes https://github.com/opencontrol/compliance-masonry/issues/131.

**Comment by pburkholder** [comment]
As the `opencontrol.yaml` scheme gets changed it would be cool to have that tracked with something in https://opencontrol/schemas as well. Currently I don't see any documentation for the schema.

**Comment by afeld** [comment]
Haha I'm glad you said it so I don't have to :trollface:

**Comment by joshuamckenty** [comment]
Patches welcome - the website is also on GitHub :) Or are you thinking we should auto generate something?

**Comment by pburkholder** [comment]
@joshuamckenty https://github.com/opencontrol/schemas/pull/40 is what I had in mind, so there it is.

**Pull request closed without merging**
