### PR TITLE
Initial Docker support

### PR DESCRIPTION
**Pull request by anweiss**
Adding Dockerfile and .dockerignore for initial Docker support.

CC @afeld

### CODE REVIEW

**Comment by afeld** [comment]
Sorry for the slow response - looks good! Doesn't seem I have the ability to add the repository to Docker Hub, even though I seem to be a member - mind giving me permissions? Thanks!

**Comment by anweiss** [comment]
@afeld ... go ahead and try it again

**Comment by anweiss** [comment]
I went ahead and set up the automated build -> https://hub.docker.com/r/opencontrolorg/compliance-masonry/. 18F org team has full permissions to reconfigure as appropriate

**Comment by jcscottiii** [comment]
@anweiss awesome!

**Pull request merged**
